export const BRAZILIAN_TIMEZONES = [
  {
    timezone: "America/Noronha",
    description: "Fernando de Noronha (UTC−2)",
  },
  { timezone: "America/Araguaina", description: "Araguaína (UTC−3)" },
  { timezone: "America/Bahia", description: "Salvador (UTC−3)" },
  { timezone: "America/Belem", description: "Belém (UTC−3)" },
  { timezone: "America/Fortaleza", description: "Fortaleza (UTC−3)" },
  { timezone: "America/Maceio", description: "Maceió (UTC−3)" },
  { timezone: "America/Recife", description: "Recife (UTC−3)" },
  { timezone: "America/Sao_Paulo", description: "São Paulo (UTC−3)" },
  { timezone: "America/Santarem", description: "Santarém (UTC−3)" },
  { timezone: "America/Boa_Vista", description: "Boa Vista (UTC−4)" },
  { timezone: "America/Campo_Grande", description: "Campo Grande (UTC−4)" },
  { timezone: "America/Cuiaba", description: "Cuiabá (UTC−4)" },
  { timezone: "America/Manaus", description: "Manaus (UTC−4)" },
  { timezone: "America/Porto_Velho", description: "Porto Velho (UTC−4)" },
  { timezone: "America/Eirunepe", description: "Eirunepé (UTC−5)" },
  { timezone: "America/Rio_Branco", description: "Acre (UTC−5)" },
];
