import { FormEvent, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useMutation, useQuery } from "@tanstack/react-query";
import { ArrowLeft, RotateCcw, Send, TestTube2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useWorkspaceManager } from "@/hooks/useWorkspaceManager";
import { PlaygroundScenario, PlaygroundSession } from "@/types/assistant-playground";
import { createPlaygroundSession, listTransitionDecisions, resetPlaygroundSession, sendPlaygroundMessage, updatePlaygroundScenario } from "@/services/agent/playground";

const initialScenario: PlaygroundScenario = { customer: { name: "Cliente de teste" }, deal: { title: "Deal de teste" }, stage: { name: "Qualificação", requiredFields: [], allowedTargetStages: [] }, fields: {}, followUps: [], calendar: { active: false, events: [], availability: [] } };
const json = (value: unknown) => JSON.stringify(value, null, 2);
const parse = (value: string, fallback: Record<string, unknown>) => { try { const parsed = JSON.parse(value); return parsed && typeof parsed === "object" ? parsed as Record<string, unknown> : fallback; } catch { return fallback; } };
const errorMessage = (error: unknown) => {
  const response = error as { response?: { status?: number; data?: { message?: string } } };
  return { status: response.response?.status, message: response.response?.data?.message };
};

export default function AssistantPlaygroundPage() {
  const { id: assistantId = "" } = useParams();
  const { workspaceId } = useWorkspaceManager();
  const apiKeyRef = useRef<HTMLInputElement>(null);
  const [sessionId, setSessionId] = useState<string>();
  const [current, setCurrent] = useState<PlaygroundSession>();
  const [draft, setDraft] = useState(false);
  const [scenario, setScenario] = useState(initialScenario);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [customerFields, setCustomerFields] = useState("{}");
  const [dealFields, setDealFields] = useState("{}");
  const decisions = useQuery({ queryKey: ["transition-decisions", assistantId, workspaceId], queryFn: () => listTransitionDecisions(assistantId, { workspaceId: workspaceId || "", limit: 20 }), enabled: !!assistantId && !!workspaceId });
  const create = useMutation({ mutationFn: () => createPlaygroundSession({ workspaceId: workspaceId || undefined, configuration: draft ? { mode: "draft", assistant: {} } : { mode: "saved", assistantId }, scenario }), onSuccess: (data) => { setSessionId(data.id); setCurrent(data); setError(""); } , onError: (response: unknown) => setError(errorMessage(response).message || "Não foi possível criar a sessão de teste.") });
  const updateScenario = useMutation({ mutationFn: (nextScenario: PlaygroundScenario) => sessionId ? updatePlaygroundScenario(sessionId, nextScenario) : Promise.resolve(undefined), onSuccess: (data) => { if (data) setCurrent(data); }, onError: () => setError("Não foi possível atualizar o cenário.") });
  const reset = useMutation({ mutationFn: () => sessionId ? resetPlaygroundSession(sessionId) : Promise.resolve(undefined), onSuccess: (data) => { if (data) setCurrent(data); setMessage(""); }, onError: (response: unknown) => setError(errorMessage(response).status === 404 ? "A sessão expirou. Crie uma nova sessão." : "Não foi possível reiniciar a conversa.") });
  const send = useMutation({ mutationFn: () => sessionId ? sendPlaygroundMessage(sessionId, message, draft ? apiKeyRef.current?.value : undefined) : Promise.reject(new Error("Crie uma sessão antes de enviar.")), onSuccess: () => { setMessage(""); setError(""); }, onError: (response: unknown) => { const status = errorMessage(response).status; setError(status === 429 ? "Limite de mensagens atingido. Tente novamente em instantes." : status === 422 ? "Informe a credencial efêmera para testar o rascunho." : status === 404 ? "A sessão expirou. Crie uma nova sessão." : "Não foi possível executar este turno."); } });
  const diagnostic = send.data;
  const saveScenario = (event: FormEvent) => { event.preventDefault(); const fields = parse(customerFields, {}); const deal = parse(dealFields, {}); const nextScenario = { ...scenario, customer: { ...scenario.customer, customFields: fields }, deal: scenario.deal ? { ...scenario.deal, ...deal } : null, fields }; setScenario(nextScenario); if (sessionId) updateScenario.mutate(nextScenario); };

  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><Link to={`/agents/${assistantId}`}><Button variant="ghost" size="sm"><ArrowLeft className="mr-1 h-4 w-4" />Voltar ao agente</Button></Link><h1 className="text-3xl font-bold">Teste aqui seu agente</h1><p className="text-muted-foreground">A conversa e os efeitos são simulados; nada é enviado a clientes ou ao pipeline.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => reset.mutate()} disabled={!sessionId || reset.isPending}><RotateCcw className="mr-2 h-4 w-4" />Nova conversa</Button><Button onClick={() => create.mutate()} disabled={create.isPending}><TestTube2 className="mr-2 h-4 w-4" />{sessionId ? "Nova sessão" : "Criar sessão"}</Button></div></div>
    {error && <p role="alert" className="rounded-md border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
    <div className="grid gap-6 xl:grid-cols-[360px_minmax(0,1fr)_420px]">
      <Card><CardHeader><CardTitle>Cenário fictício</CardTitle><CardDescription>IDs ficam restritos a esta área administrativa.</CardDescription></CardHeader><CardContent><form className="space-y-3" onSubmit={saveScenario}><Label htmlFor="customer-name">Cliente</Label><Input id="customer-name" value={scenario.customer.name} onChange={(event) => setScenario({ ...scenario, customer: { ...scenario.customer, name: event.target.value } })} /><Label htmlFor="deal-title">Deal (vazio para remover)</Label><Input id="deal-title" value={scenario.deal?.title || ""} onChange={(event) => setScenario({ ...scenario, deal: event.target.value ? { ...(scenario.deal || {}), title: event.target.value } : null })} /><Label htmlFor="stage-name">Etapa atual</Label><Input id="stage-name" value={scenario.stage.name} onChange={(event) => setScenario({ ...scenario, stage: { ...scenario.stage, name: event.target.value } })} /><Label htmlFor="fields-json">Campos preenchidos (JSON)</Label><Textarea id="fields-json" value={customerFields} onChange={(event) => setCustomerFields(event.target.value)} /><Label htmlFor="deal-json">Dados do deal (JSON)</Label><Textarea id="deal-json" value={dealFields} onChange={(event) => setDealFields(event.target.value)} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={scenario.calendar.active} onChange={(event) => setScenario({ ...scenario, calendar: { ...scenario.calendar, active: event.target.checked } })} />Calendário disponível</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft} onChange={(event) => setDraft(event.target.checked)} />Testar como rascunho</label>{draft && <div><Label htmlFor="draft-key">Credencial efêmera</Label><Input id="draft-key" ref={apiKeyRef} type="password" autoComplete="off" placeholder="Enviada somente neste turno" /><p className="mt-1 text-xs text-muted-foreground">Ela não é salva, exibida no diagnóstico nem incluída na URL.</p></div>}<Button type="submit" variant="outline" className="w-full" disabled={updateScenario.isPending}>Aplicar cenário</Button></form></CardContent></Card>
      <Card className="min-h-[560px]"><CardHeader><CardTitle>Conversa simulada</CardTitle><CardDescription>{current ? `Sessão criada às ${new Date(current.createdAt).toLocaleTimeString()}` : "Crie uma sessão para iniciar."}</CardDescription></CardHeader><CardContent className="flex h-[480px] flex-col"><div className="flex-1 space-y-3 overflow-y-auto pr-1">{(diagnostic?.transcript ?? current?.transcript)?.length ? (diagnostic?.transcript ?? current?.transcript ?? []).map((turn, index) => <div key={`${turn.createdAt}-${index}`} className={turn.role === "user" ? "ml-auto max-w-[85%] rounded-lg bg-primary p-3 text-primary-foreground" : "mr-auto max-w-[85%] rounded-lg bg-muted p-3"}><p className="text-xs opacity-70">{turn.role === "user" ? "Cliente" : "Agente"}</p><p className="whitespace-pre-wrap text-sm">{turn.content}</p></div>) : <p className="pt-20 text-center text-sm text-muted-foreground">O transcript aparecerá aqui.</p>}</div><form className="mt-4 flex gap-2" onSubmit={(event) => { event.preventDefault(); if (message.trim()) send.mutate(); }}><Input aria-label="Mensagem do cliente" value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Escreva como o cliente..." disabled={!sessionId || send.isPending} /><Button type="submit" size="icon" disabled={!sessionId || !message.trim() || send.isPending}><Send className="h-4 w-4" /></Button></form></CardContent></Card>
      <Card><CardHeader><CardTitle>Diagnóstico do turno</CardTitle><CardDescription>Prompt redigido e resultados simulados.</CardDescription></CardHeader><CardContent><Tabs defaultValue="result"><TabsList className="w-full"><TabsTrigger value="result">Resultado</TabsTrigger><TabsTrigger value="prompt">Prompt</TabsTrigger><TabsTrigger value="history">Histórico</TabsTrigger></TabsList><TabsContent value="result" className="space-y-3"><div><Label>Resposta visível</Label><p className="mt-1 rounded bg-muted p-2 text-sm">{diagnostic?.visibleResponse || "Aguardando turno."}</p></div><div><Label>Decisão</Label><pre className="mt-1 max-h-36 overflow-auto rounded bg-muted p-2 text-xs">{json(diagnostic?.decision || {})}</pre></div><div><Label>Ferramentas e chamadas simuladas</Label>{diagnostic?.simulatedToolCalls?.length ? diagnostic.simulatedToolCalls.map((call) => <div key={call.id} className="mt-1 rounded border p-2 text-xs"><b>{call.name}</b> · {call.durationMs}ms · {call.stateChanged ? "alterou estado" : "sem alteração"}<pre className="mt-1 overflow-auto">{json({ arguments: call.validatedArguments, result: call.result })}</pre></div>) : <p className="text-sm text-muted-foreground">Nenhuma chamada neste turno.</p>}</div><div className="flex flex-wrap gap-1">{diagnostic?.warnings?.map((warning) => <Badge key={warning} variant="secondary">{warning}</Badge>)}{diagnostic?.errors?.map((item) => <Badge key={item.code} variant="destructive">{item.code}: {item.message}</Badge>)}</div>{diagnostic?.latencies?.totalMs !== undefined && <p className="text-xs text-muted-foreground">Latência total: {diagnostic.latencies.totalMs}ms</p>}</TabsContent><TabsContent value="prompt"><p className="text-sm text-muted-foreground">Somente seções seguras do prompt são expostas aqui; credenciais, IDs técnicos e contexto interno não são exibidos.</p><pre className="mt-3 max-h-80 overflow-auto rounded bg-muted p-2 text-xs">{json(diagnostic?.promptSections || { platformPolicies: "Redigido", administratorConfiguration: "Redigido", capabilities: "Redigido", currentStage: scenario.stage.name, internalContext: "Redigido" })}</pre></TabsContent><TabsContent value="history" className="space-y-2">{decisions.isLoading && <p className="text-sm text-muted-foreground">Carregando histórico…</p>}{decisions.data?.items?.map((decision) => <details key={decision.id} className="rounded border p-2 text-sm"><summary><Badge variant="secondary">{decision.result}</Badge> {new Date(decision.createdAt).toLocaleString()}</summary><p className="mt-2">Critérios faltantes: {decision.missingCriteria.join(", ") || "nenhum"}</p><p>Evidências expiram em 90 dias.</p>{decision.evidence.map((evidence, index) => <pre key={index} className="mt-1 overflow-auto rounded bg-muted p-1 text-xs">{evidence}</pre>)}</details>)}{!decisions.isLoading && !decisions.data?.items?.length && <p className="text-sm text-muted-foreground">Nenhuma decisão encontrada.</p>}</TabsContent></Tabs></CardContent></Card>
    </div>
  </div>;
}
